import {ProviderAuth} from '@hooks/useAuth'
import Nav from '@common/Nav'
import Header from '@components/Header'
import '@styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      
      <ProviderAuth>
      <body className={inter.className}>
        <div>
          <Header />
          <Nav/>
        </div>
        {children}
      </body>
      </ProviderAuth>
    </html>
  )
}
